restart-times: 2
max-jobs-per-second: 10
max-status-checks-per-second: 10
latency-wait: 60
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: False
scheduler: greedy

default-resources:
  - mem_mb=4000
set-resources:
  - high_memory_rule:mem_mb=8000
  - low_memory_rule:mem_mb=2000