restart-times: 2
max-jobs-per-second: 10
max-status-checks-per-second: 10
latency-wait: 60
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy

default-resources:
  - mem_mb=6000
set-resources:
  - high_memory_rule:mem_mb=12000
  - low_memory_rule:mem_mb=2000